### PR TITLE
Render figures and tables qmds even if rdas are missing

### PR DESCRIPTION
**Pull request by sbreitbart-NOAA**
# What is the feature?
* Render figures and tables qmds even if rdas are missing. This is working for figures only, though; with tables, it says that indices_cap not found (analogous error isn't generated for figures qmd). Struggling to find the error.

# How have you implemented the solution?
* Checking for rdas with for loops for each figure/table rda

# Does the PR impact any other area of the project, maybe another repo?
* No

### CODE REVIEW

**Comment by sbreitbart-NOAA** [comment]
@Schiano-NOAA could you please take a look and see if you can find the bug?

**Comment by Schiano-NOAA** [comment]
> @Schiano-NOAA could you please take a look and see if you can find the bug?

@sbreitbart-NOAA Looks like the change from main that fixed this issue wasn't pulled to this branch. You can either rebase from main or just change the following line in the DESCRIPTION file from true to false

https://github.com/nmfs-ost/asar/blob/0b3e0e5de974a5082d2a31cf1677a9da59728172/DESCRIPTION#L60

**Comment by sbreitbart-NOAA** [comment]
> Config/testthat/parallel: true

Ah, thanks for this. I meant, can you help find the bug preventing the tables qmd from rendering? The figures one renders just fine. But with tables, it says that indices_cap not found (analogous error isn't generated for figures qmd).

**Comment by Schiano-NOAA** [comment]
@sbreitbart-NOAA Ahh I gotcha now. Yeah I can take a look in a minute

**Comment by Schiano-NOAA** [comment]
@sbreitbart-NOAA Is this PR finished?

**Review by Schiano-NOAA — APPROVED** [review]
Looks a1

**Comment by sbreitbart-NOAA** [comment]
> @sbreitbart-NOAA Is this PR finished?

Yup! Will merge

**Pull request merged**
